### ISSUE TITLE
As a <JavaScript developer>, I want to <see a simple example of an Offline First Progressive Web App built using Preact and PouchDB> so that <I can build my own Offline First Progressive Web App>.

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list#4]

**Comment by bradley-holt** [comment]
@rajrsingh Is this still in progress? Or should we consider it complete and close it?

**Comment by rajrsingh** [comment]
Completed. We didn't close because we said product owner should be the only one to close issues.

**Comment by bradley-holt** [comment]
@rajrsingh I only asked because it's still in the "In Progress" column. I'll move it to "Done" and then close it.
