### ISSUE TITLE
Style Guides

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list#83]
Style guides for the various demo app implementations needs to be identified. This should be added as a "Style Guide" section to the `README`.

General guidelines:

* Where possible, we should maintain a consistent style between the different demo app implementations.
* However, where there is a style that is common for a particular type of application we should defer to that style.

Potential existing style guides to choose from:

* [Material design](https://material.io/guidelines/)
* [Bootstrap](http://getbootstrap.com/)
* [Carbon Design System](http://carbondesignsystem.com/)
* [iOS design themes](https://developer.apple.com/ios/human-interface-guidelines/overview/design-principles/)

Has an appropriate style guide been identified for the following implementations?

- [ ] Vanilla JS
- [ ] Polymer
- [ ] React
- [ ] Preact
- [ ] Vue.js
- [ ] Ember.js
- [ ] React Native
- [ ] Ionic
- [ ] Cordova
- [ ] Swift
- [ ] Kotlin
- [ ] Electron

Please discuss as comments on this ticket.

**Comment by chrisdhanaraj** [comment]
I'll jump in as the dev lead for Carbon :) We have two (official) implementations of Carbon

- VanillaJS - https://github.com/carbon-design-system/carbon-components
- ReactJS - https://github.com/carbon-design-system/carbon-components-react

**Comment by bradley-holt** [comment]
I've taken an initial stab at matching up each stack with an existing style guide (and implementation, where appropriate):
https://github.com/ibm-watson-data-lab/shopping-list#style-guides

**Comment by vabarbosa** [comment]
the style guide has been updated accordingly for each stack  

- https://github.com/ibm-watson-data-lab/shopping-list#style-guides

but are subject to change as implementation begins and additional research is done for each stack.
