### ISSUE TITLE
Create a CONTRIBUTING.md Template

### ISSUE THREAD

**Issue by bradley-holt** [ibm-watson-data-lab/shopping-list#99]
Create a `CONTRIBUTING.md` template based on:
https://github.com/ibm-watson-data-lab/shopping-list-polymer-pouchdb/blob/master/CONTRIBUTING.md

**Comment by markstur** [comment]
We've simplified the journey template CONTRIBUTING.md so that it does not need to be modified for each project and can be copied in as-is from https://github.ibm.com/developer-journeys/journey-docs/blob/master/content/markdown_files/CONTRIBUTING.md.  Same with MAINTAINERS.md.
